### PR TITLE
Newsweek clone

### PR DESCRIPTION
**Pull request by PhiPhiPhi**
Bootstrap project (Newsweek-clone) completed. Please review. Thanks!

### CODE REVIEW

**Review by MauricioRobayo — CHANGES_REQUESTED** [review]
This is awesome work! Congratulations, very well done 👏 😄 .

I consider you have made an amazing job, just one enhancement to do:

image

Your CSS file is 1252 lines long. There is no way of going through this just with Bootstrap, and a lot of customization is needed. But the main objective is to try to use the most of Bootstrap, there is a lot of custom CSS you could get rid of by using Bootstrap.

- [ ] Reduce your custom CSS by using more of Bootstrap classes.

This sections might be especially useful:

- https://getbootstrap.com/docs/4.3/utilities/spacing/
- https://getbootstrap.com/docs/4.3/components/card/

**Status**: Request changes.

**Comment by PhiPhiPhi** [comment]
Changes made and pushed

**Comment by MauricioRobayo** [comment]
@PhiPhiPhi Remember to submit a new code review form after you fix the requested changes 👍 .

Another TSE will check if everything is fine or if there are more changes required.

**Review by nikasulo — APPROVED** [review]
# Fantastic work man! :rocket: 
This is really great work I must say, very neatly styled page, neatly written code and great attention to detail :smile:.

#### Please merge :+1:

**Comment by PhiPhiPhi** [comment]
Thank you!

**Pull request merged**
